<?xml version="1.0" encoding="ASCII"?>
<graphml:GraphML xmlns:graphml="http://www.example.org/graphml">
  <graph id="some graph id 1" name="some graph name 1">
    <nodes id="some node id 2" name="some node name 2"/>
    <nodes id="some node id 3" name="some node name 3"/>
    <nodes/>
  </graph>
</graphml:GraphML>
