<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BookStorePackage" nsURI="http:///com.ibm.dynamic.example.bookstore.ecore" nsPrefix="bookStore">
  <eClassifiers xsi:type="ecore:EClass" name="Store">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="Store name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books0" containment="true">
      <eType xsi:type="ecore:EClass" href="#//Book"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books1" containment="true">
      <eType xsi:type="ecore:EClass" href="#//Book"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workers0" containment="true">
      <eType xsi:type="ecore:EClass" href="#//Worker"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workers1" containment="true">
      <eType xsi:type="ecore:EClass" href="#//Worker"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" defaultValueLiteral="Book1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" defaultValueLiteral="Book2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Worker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workerName" defaultValueLiteral="Worker Name 1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Worker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workerName" defaultValueLiteral="Worker Name 2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
